// game/fallback/en/themes/badExcuses.js

export const badExcusesPack = {
    theme: "Bad Excuses For Being Late",
    battlePrompts: [
        "Urgent text sent to the boss at 9:05 AM:",
        "Official police report explaining your morning commute delay:",
        "What the militant squirrel demanded in exchange for your car keys:",
        "The #1 reason your GPS navigated you directly into a pond:",
        "Emergency excuse when trapped in an elevator with a barbershop quartet:",
        "What the time-traveling wizard whispered before vanishing:",
        "The absurd excuse given to the meeting moderator:",
        "What the street mime did to hold you hostage for an hour:",
        "The shocking confession written on your late pass:",
        "Why your alarm clock officially refused to make any noise:",
        "What the rogue flock of pigeons communicated to the traffic officer:",
        "The emergency reason you were detained by a confused magician:",
        "What the talking cat told you during the morning standoff:",
        "The bizarre excuse whispered to your angry teacher:",
        "What the runaway hot air balloon pilot screamed down at you:",
        "The #1 reason your shadow decided to stay in bed today:",
        "Official testimony about the interdimensional portal in the kitchen:",
        "What the rogue drone commanded you to do at the intersection:",
        "The chaotic explanation given to the furious wedding planner:",
        "What the sentient coffee machine demanded before dispensing caffeine:",
        "The wild excuse given for alphabetizing your entire spice rack:",
        "What the aggressive raccoon demanded before moving off your windshield:",
        "The emergency radio broadcast explaining your traffic delay:",
        "What you screamed while chasing a runaway wheel of cheese:",
        "The official notice posted on the broken subway car:",
        "What the mysterious glowing orb in the hallway told you:",
        "The desperate voice note sent to your angry romantic date:",
        "Why your shoes decided to declare sovereign independence:",
        "What the angry park duck quacked in your face for twenty minutes:",
        "The emergency plea made to the city traffic controller:",
        "What the street performer promised before locking you in a fake box:",
        "The ridiculous reason you spent forty minutes in a revolving door:",
        "What the confused ghost needed help with before letting you leave:",
        "The secret mission assigned to you by the city squirrel council:",
        "What your dog told the neighbors while framing the cat for tardiness:",
        "The frantic text sent after accidentally joining a bicycle marathon:",
        "Why the city bus driver suddenly decided to take everyone to the beach:",
        "What the angry statue whispered when you lost the staring contest:",
        "The #1 excuse given to the flight attendant when boarding late:",
        "What the neighborhood fortune teller predicted about your morning:",
        "The bizarre explanation for why you were wearing two left boots:",
        "What the emergency plumber shouted before disappearing into the wall:",
        "The chaotic excuse for why your car was covered in pancake batter:",
        "What the angry goose demanded as a toll on the pedestrian bridge:",
        "The dramatic excuse written in a note to your team lead:",
        "What you yelled to the barista while fleeing an angry swarm of bees:",
        "The official excuse for accidentally crossing an international border:",
        "What the rebellious toaster burned onto your morning toast:",
        "The frantic excuse given when arriving three hours late to brunch:",
        "The final ridiculous statement in your workplace apology email:"
    ]
};
