// game/fallback/en/themes/chaoticDiner.js

export const chaoticDinerPack = {
    theme: "Haunted 24-Hour Diner",
    battlePrompts: [
        "Special of the day written on the greasy diner chalkboard:",
        "The #1 survival rule for working the 3 AM ghost shift:",
        "Complaint shouted by the angry poltergeist in booth #4:",
        "1-star Yelp review left by a traveling vampire truck driver:",
        "Warning sign taped onto the cursed vintage jukebox:",
        "What the graveyard-shift waitress muttered while pouring coffee:",
        "The secret ingredient in the bottomless cup of phantom coffee:",
        "What the neon sign flickers when the demons arrive at midnight:",
        "The emergency announcement over the diner's crackling intercom:",
        "What the floating plate of greasy hashbrowns whispered:",
        "The #1 rule for using the haunted diner restroom:",
        "Catchphrase shouted by the zombie short-order cook:",
        "Review written by a werewolf about the midnight meatloaf:",
        "Warning sticker on the side of the blood-red condiment dispenser:",
        "What the possessed milkshake blender screamed at the manager:",
        "The secret deal made between the diner manager and the Grim Reaper:",
        "Customer complaint filed by the headless trucker at the counter:",
        "What the flickering hallway exit sign warned patrons about:",
        "The #1 item banned from the Haunted Diner kids' menu:",
        "Catchphrase used by the demon line-cook flipping flapjacks:",
        "Review left by an exorcist after eating the graveyard pie:",
        "What the haunted cash register printed on the midnight receipt:",
        "The desperate SOS message carved into the laminate counter:",
        "Warning sign hung outside the walk-in freezer of doom:",
        "What the phantom dishwasher murmured behind the steam:",
        "The #1 excuse given for why the maple syrup is glowing green:",
        "Catchphrase shouted by the banshee hostess seating guests:",
        "Review written for the 24-hour breakfast by a ghost hunter:",
        "What the diner floor mop whispered while cleaning up ectoplasm:",
        "The secret ritual required to get a clean glass of water:",
        "Warning label on the bottom of the cursed apple turnover:",
        "What the poltergeist threw across the dining room at 4 AM:",
        "The emergency protocol for when the pancake batter becomes sentient:",
        "Review left by a demon prince about the spicy chili cheese fries:",
        "What the weary diner owner told the local police officer:",
        "The #1 rule for tipping the ghostly busboy at table seven:",
        "Catchphrase printed on the Haunted Diner staff t-shirts:",
        "Warning etched onto the greasy napkin dispenser:",
        "What the phantom trucker shouted before disappearing into thin air:",
        "The secret ingredient that keeps the coffee pot boiling forever:",
        "Review written by the local mayor about the midnight waffle special:",
        "What the jukebox played when all the lights suddenly went out:",
        "The #1 rule for ordering eggs over-easy during a full moon:",
        "Catchphrase shouted by the werewolf busboy dropping a tray:",
        "Warning sign on the back door leading to the spectral alleyway:",
        "What the floating butter knife whispered to the fresh toast:",
        "The emergency instructions for surviving the 5 AM vampire rush:",
        "Review left by a skeleton critic about the greasy burger combo:",
        "What the diner cat hissed at the shadow in the corner booth:",
        "The final legendary slogan of the Haunted 24-Hour Diner:"
    ]
};
