// game/fallback/en/themes/everydayObjects.js

export const everydayObjectsPack = {
    theme: "Everyday Objects, Epic Backstories",
    battlePrompts: [
        "Warning label on the breakroom coffee mug:",
        "The #1 ancient decree of the Living Room Remote Control:",
        "1-star Yelp review left for this office stapler:",
        "What the rubber duck whispered before plunging into battle:",
        "The secret origin story of the lonely lost sock:",
        "Motivational slogan on the rusty dumbbell:",
        "The dark secret hidden inside the office junk drawer:",
        "Complaint shouted by the clogged bathroom drain:",
        "Final words spoken by the incandescent lightbulb:",
        "The desperate plea carved into the kitchen cheese grater:",
        "Official warning sign on the office paperclip holder:",
        "The shocking confession of the living room couch cushions:",
        "What the bathroom mirror screams every morning at 7 AM:",
        "The secret battle cry of the kitchen toaster:",
        "1-star review written by an angry desk chair:",
        "What the ceiling fan gossips about when you leave the room:",
        "The top secret mission of the refrigerator magnets:",
        "Customer complaint filed against the hallway welcome mat:",
        "What the television remote whispered to the batteries:",
        "The solemn vow made by a solitary Lego brick:",
        "Warning printed on the cursed office water cooler:",
        "The tragic last will of a sharpened yellow pencil:",
        "What the bedroom alarm clock yells to start your day:",
        "The ancient prophecy inscribed on the kitchen spork:",
        "Emergency broadcast sent by the wifi router:",
        "The secret identity of the kitchen can opener:",
        "What the dust bunny under the bed knows about humanity:",
        "Warning tag on the aggressive vacuum cleaner:",
        "The #1 rule in the secret society of coat hangers:",
        "What the bathroom toothbrush actually thinks of your life:",
        "Slogan on the billboard for the rebellious broom:",
        "The shocking headline in the Refrigerator News:",
        "What the kitchen sponge murmured after washing a burnt pan:",
        "The sacred oath sworn by the hallway key rack:",
        "Warning sign posted on the rebellious microwave:",
        "The philosophical conclusion reached by the bathroom scale:",
        "What the front doorknob whispered to the burglar:",
        "The 1-star review given by a pair of sunglasses:",
        "The secret manifesto found inside the dishwasher filter:",
        "What the car keys yelled from between the car seats:",
        "The legendary prophecy of the bottle opener:",
        "Warning sticker on the bottom of an electric kettle:",
        "What the laundry basket mutters when overloaded with clothes:",
        "The emergency distress signal sent by the smart thermostat:",
        "What the kitchen knife set whispered during the night:",
        "The dramatic monologue delivered by the bath towel:",
        "What the fire extinguisher screamed during the false alarm:",
        "The secret confession of the bedroom ceiling fan:",
        "Warning etched onto the side of an old cardboard box:",
        "The final heroic slogan of the kitchen roll:"
    ]
};
