// game/fallback/en/themes/historicalFigures.js

export const historicalFiguresPack = {
    theme: "If Historical Figures Had Modern Jobs",
    battlePrompts: [
        "1-star Yelp review written by Julius Caesar for a fast-food drive-thru:",
        "Slogan on the billboard for Napoleon's Silicon Valley startup:",
        "The #1 rule in Sun Tzu's competitive esports training camp:",
        "Title of Albert Einstein's viral TikTok life-hack series:",
        "Warning sign in the kitchen of Gordon Ramsay and Leonardo da Vinci:",
        "Catchphrase shouted by Henry VIII as a reality talent show judge:",
        "Customer complaint filed by Marie Curie against her IT department:",
        "Slogan on Blackbeard the Pirate's modern corporate tax consulting firm:",
        "The #1 piece of dating advice from Casanova's relationship blog:",
        "Title of Socrates's aggressive motivational podcast:",
        "Review written by Cleopatra for a trendy luxury spa resort:",
        "Slogan on Benjamin Franklin's energy drink company van:",
        "The #1 rule in a Spartan warrior's modern CrossFit gym:",
        "Catchphrase used by Abraham Lincoln in his courtroom commercial:",
        "Title of Edgar Allan Poe's weekly true-crime podcast:",
        "Warning label on Isaac Newton's organic apple cider stand:",
        "The #1 piece of career advice from Machiavelli's LinkedIn post:",
        "Slogan on Joan of Arc's fire safety consulting truck:",
        "Review written by Michelangelo about a cheap motel bathroom:",
        "The secret ingredient in Wolfgang Mozart's artisanal food truck:",
        "Title of Nikola Tesla's viral crowdfunding campaign:",
        "The #1 customer rule in Sigmund Freud's coffee shop:",
        "Catchphrase used by Genghis Khan during an aggressive corporate merger:",
        "Slogan on Mark Twain's modern travel booking website:",
        "Warning printed on a perfume bottle formulated by Mata Hari:",
        "Title of Hercules's extreme personal training video series:",
        "The #1 legal principle at Hammurabi & Associates law firm:",
        "Review written by Christopher Columbus about Google Maps:",
        "Title of Queen Elizabeth I's royal reality television show:",
        "Slogan on Plato's subterranean escape room business:",
        "The #1 warning sign at Johnny Appleseed's modern garden center:",
        "Catchphrase used by Rasputin in his late-night infomercial:",
        "Title of H.G. Wells's new sci-fi virtual reality video game:",
        "Slogan on Nostradamus's unpredictable weather forecast app:",
        "Review written by King Midas for a local hardware store:",
        "The #1 rule in Merlin's Las Vegas magic casino show:",
        "Title of H.P. Lovecraft's wholesome children's storybook:",
        "Slogan on St. Francis of Assisi's luxury pet hotel billboard:",
        "Catchphrase shouted by Ernest Hemingway at his tropical tiki bar:",
        "The #1 rule in Sherlock Holmes's cybersecurity agency:",
        "Review written by Beethoven for a noisy pair of wireless headphones:",
        "Slogan on Alexander the Great's package delivery courier fleet:",
        "Title of Confucius's weekly productivity newsletter:",
        "Warning sign posted at Willy Wonka's modern candy research lab:",
        "The #1 rule in Noah's exotic pet adoption center:",
        "Catchphrase shouted by a Viking warrior working in customer service:",
        "Title of Dante's travel guide to morning commuter traffic:",
        "Slogan on Wright Brothers' commercial drone racing team:",
        "Review written by King Arthur for a round conference room table:",
        "The final inspirational quote from Charles Darwin's pet store:"
    ]
};
