// game/fallback/en/themes/terribleSuperpowers.js

export const terribleSuperpowersPack = {
    theme: "Terrible Superpowers",
    battlePrompts: [
        "Warning label on Captain Mediocre's budget superhero suit:",
        "The embarrassing secret weakness of the world's most disappointing hero:",
        "1-star review left for the Superhero 911 Emergency Hotline:",
        "What the Condiment King whispered before spraying lukewarm mustard:",
        "The #1 rule in the Society of Inconvenient Metahumans:",
        "Catchphrase shouted by the hero who can only fly downhill:",
        "The tragic backstory of the hero whose pinky toes have super strength:",
        "Warning sign posted outside the Dairy Telekinesis Master's lair:",
        "What the invisible hero muttered while someone was looking right at them:",
        "The desperate emergency call made by Glitter-Fingers:",
        "Motivational slogan on the Damp Sock Villain's billboard:",
        "What the hero who speaks only in passive-aggressive notes wrote:",
        "The #1 rule for fighting crime with a completely normal golden retriever:",
        "Review written for the hero who can only summon lukewarm tap water:",
        "What the superhero who reads only boring thoughts overheard:",
        "The villainous demand made by the Shoelace-Untying Mastermind:",
        "Warning tag on the force field generator made of wet paper napkins:",
        "Catchphrase used by the hero who turns into a garden slug for 24 hours:",
        "The embarrassing confession made by Captain Microwave-Vision:",
        "What the hero who talks to houseplants warned the mayor about:",
        "The #1 rule of the hero whose superpower is predicting toast landings:",
        "Slogan on the truck of the hero who creates non-magical parking spots:",
        "Review left by a victim of the 10-Second Instant Love Ray:",
        "What the hero who regenerates while tasting burnt toast screamed:",
        "The tragic origin story of the crime fighter who knows exact postage:",
        "Warning painted on the side of Doctor Lukewarm's secret hovercraft:",
        "What the hero whose voice becomes squeaky when shrinking shouted:",
        "The villainous manifesto of the evil Bookshelf Reorganizer:",
        "Catchphrase used by the hero who communicates solely with the color beige:",
        "The #1 tactical rule of the hero whose speed has no brakes:",
        "Review written for the crimefighter who makes villains mildly itchy:",
        "What the hero who summons random lost keys found in the street:",
        "The dramatic speech delivered by Captain Perfectly-Folded-Sheet:",
        "Warning label on the budget teleporter that lands three feet to the left:",
        "What the superhero who can only talk to squirrels argued about:",
        "The secret weakness of the vigilante powered by bus schedules:",
        "Catchphrase shouted by the hero who can x-ray only gingerbread men:",
        "The villainous threat issued by the Master of Minor Delays:",
        "What the hero who makes people forget the last 5 seconds said twice:",
        "The #1 survival rule in a battle against the Static Electricity Bandit:",
        "Review left for the vigilante who fights crime with a megaphone:",
        "What the superhero whose fingernails grow at will complained about:",
        "The tragic confession of the hero powered by lukewarm chamomile tea:",
        "Catchphrase used by the crimefighter who can only talk in questions:",
        "Warning sticker on the side of the Sub-Zero Fridge-Opening Hero:",
        "What the super-intelligent hamsters demanded in exchange for world peace:",
        "The #1 rule in the League of Extremely Disappointing Champions:",
        "Review written by a rescued hostage about Captain Dramatic Sigh:",
        "What the villain who can only summon aggressive geese threatened to do:",
        "The final heroic slogan of the city's cheapest masked crusader:"
    ]
};
