// game/fallback/en/themes/unusualRecipes.js

export const unusualRecipesPack = {
    theme: "Unusual Recipes",
    battlePrompts: [
        "Step #1 in Grandma's recipe for 'Instant Regret' hot sauce:",
        "Warning label on the chef's cauldron of singing potato soup:",
        "1-star review left for the talking chocolate birthday cake:",
        "The #1 secret ingredient in the alien diplomat's breakfast smoothie:",
        "What the salad murmured while actively climbing out of the bowl:",
        "The disastrous first instruction for baking invisible blueberry muffins:",
        "Warning printed on the jar of 'Bravery Broth':",
        "What the vampire chef told the waiter about the garlic bread:",
        "Customer complaint filed against the opera-singing sourdough loaf:",
        "The secret ingredient that gives you a magnificent temporary beard:",
        "Step #3 in the recipe for coffee that makes you more tired:",
        "Review written for the pizza that predicts your financial future:",
        "What the mad scientist whispered into the boiling lasagna pot:",
        "The #1 rule for preparing a gourmet banquet for friendly ghosts:",
        "Warning tag on the chewing gum that never loses its flavor:",
        "What the monster ordered at the midnight drive-thru window:",
        "The chaotic ingredient added to the royal wedding punch bowl:",
        "Step #2 in creating cookies that let you speak with your past self:",
        "Review left by an astronaut about zero-gravity floating tacos:",
        "What the dragon chef roared before lighting the barbecue grill:",
        "The #1 warning sign posted in the wizard's culinary school:",
        "What the jelly vibrated when the music started playing:",
        "The secret spice blend in the detective's truth-serum stew:",
        "Customer review of the soup that tells a bad dad joke every spoonful:",
        "What the pastry chef screamed when the croissant sprouted wings:",
        "Step #4 in cooking a potato so it tastes like a glazed donut:",
        "The emergency recall notice issued for laughing dessert pudding:",
        "What the robot host served at its annual birthday party:",
        "The #1 rule for handling cheese that has gained sentience:",
        "Review written for the tea that explains confusing movie plots:",
        "What the street food vendor shouted while deep-frying a wristwatch:",
        "Warning etched into the wooden spoon of the goblin soup master:",
        "The secret ingredient in the supervillain's celebration cake:",
        "Step #1 in the recipe for bread that helps you find lost keys:",
        "What the waiter whispered about the chef's glowing green risotto:",
        "Customer complaint regarding the shape-shifting ice cream cone:",
        "The #1 ingredient banned from the international chili cook-off:",
        "Review left for the sandwich that allows you to understand squirrels:",
        "What the baker screamed when the gingerbread army marched away:",
        "Warning label on the bottle of 'Liquid Luck' soda:",
        "The secret recipe for hot dog toppings in the year 3000:",
        "What the magical lollipop tasted like on the tenth lick:",
        "Step #5 in baking a pie that reveals a glimpse of another dimension:",
        "The #1 rule for eating soup with a magical singing spoon:",
        "Review written for the restaurant whose food changes with your mood:",
        "What the pirate cook threw into the cauldron during a storm:",
        "Warning sign in the kitchen of the time-traveler's diner:",
        "The secret ingredient in the goblin's enchanted mac and cheese:",
        "What the bartender shouted before serving a flaming volcanic cocktail:",
        "The final culinary advice found in the ancient cursed cookbook:"
    ]
};
