// game/fallback/words.js

export const FALLBACK_WORDS = {
    en: [
        // Action & Object Phrases (2-4 words)
        ["a", "big", "red", "ball"],
        ["the", "cat", "sat", "on", "the", "mat"],
        ["my", "hovercraft", "is", "full", "of", "eels"],
        ["what", "is", "your", "secret", "plan"],
        ["an", "unexpected", "space", "journey"],
        ["we", "should", "build", "a", "giant", "fort"],
        ["the", "secret", "ingredient", "is", "pure", "chaos"],
        ["once", "upon", "a", "midnight", "snack"],
        ["in", "a", "galaxy", "far", "away"],
        ["the", "answer", "is", "suspiciously", "simple"],
        ["why", "did", "the", "chicken", "start", "a", "riot"],
        ["never", "trust", "a", "dancing", "badger"],
        ["a", "wizard", "is", "always", "dramatically", "late"],
        ["speak", "friend", "and", "drop", "the", "pizza"],
        ["the", "ultimate", "power", "of", "awkward", "silence"],
        ["a", "heroic", "sacrifice", "for", "tacos"],
        ["I", "think", "therefore", "I", "panic"],
        ["the", "truth", "is", "hidden", "in", "the", "fridge"],
        ["there", "is", "no", "escape", "from", "mondays"],
        ["unleash", "the", "ancient", "laser", "potato"],
        ["definitely", "not", "three", "raccoons", "in", "a", "trenchcoat"],
        ["press", "the", "red", "button", "immediately"],
        ["screaming", "internally", "at", "maximum", "volume"],
        ["professional", "couch", "potato", "champion"],
        ["accidental", "time", "travel", "incident"],
        ["extremely", "loud", "and", "incredibly", "clumsy"],
        ["dangerously", "cheesy", "mastermind", "plot"],
        ["running", "in", "circles", "with", "scissors"],
        ["summoning", "a", "friendly", "neighborhood", "dragon"],
        ["bribing", "the", "security", "guard", "with", "donuts"],
        ["stealing", "all", "the", "left", "shoes"],
        ["exploding", "with", "uncontrollable", "enthusiasm"],
        ["a", "tragic", "misunderstanding", "about", "gravity"],
        ["fighting", "crime", "in", "fluffy", "slippers"],
        ["whispering", "secrets", "to", "the", "toaster"],

        // Essential Connectors, Modifiers, Pronouns & Auxiliaries
        ["and", "also", "furthermore", "together"],
        ["but", "however", "although", "except"],
        ["because", "therefore", "since", "why"],
        ["always", "forever", "constantly", "everywhere"],
        ["never", "nobody", "nowhere", "nothing"],
        ["secretly", "quietly", "suspiciously", "mysteriously"],
        ["very", "extremely", "totally", "absolutely"],
        ["without", "against", "towards", "under"],
        ["our", "their", "your", "my"],
        ["suddenly", "instantly", "quickly", "finally"],
        ["really", "truly", "actually", "honestly"],
        ["everyone", "someone", "anyone", "everything"],
        ["with", "this", "that", "these"],
        ["almost", "nearly", "barely", "hardly"],
        ["too", "much", "more", "less"]
    ],
    uk: [
        // Action & Object Phrases (2-4 words)
        ["великий", "червоний", "м'яч"],
        ["кіт", "сидів", "на", "теплому", "килимку"],
        ["мій", "корабель", "на", "повітряній", "подушці"],
        ["який", "твій", "хитрий", "план"],
        ["несподівана", "космічна", "подорож"],
        ["нова", "епічна", "надія"],
        ["ми", "повинні", "збудувати", "величезний", "форт"],
        ["секретний", "інгредієнт", "це", "чистий", "хаос"],
        ["одного", "разу", "опівночі", "на", "кухні"],
        ["в", "далекій", "галактиці", "без", "вайфаю"],
        ["відповідь", "підозріло", "проста"],
        ["чому", "курка", "влаштувала", "бунт"],
        ["ніколи", "не", "довіряй", "танцюючому", "борсуку"],
        ["чарівник", "завжди", "епічно", "запізнюється"],
        ["скажи", "пароль", "і", "віддай", "піцу"],
        ["велика", "сила", "незручного", "мовчання"],
        ["героїчна", "битва", "за", "останній", "пиріжок"],
        ["я", "мислю", "отже", "я", "панікую"],
        ["істина", "захована", "в", "холодильнику"],
        ["немає", "порятунку", "від", "ранкового", "будильника"],
        ["активувати", "секретну", "лазерну", "картоплю"],
        ["точно", "не", "три", "єноти", "в", "плащі"],
        ["тисни", "на", "червону", "кнопку", "негайно"],
        ["кричати", "в", "подушку", "на", "повну", "гучність"],
        ["абсолютний", "чемпіон", "диванної", "боротьби"],
        ["випадковий", "стрибок", "у", "часі"],
        ["надзвичайно", "голосно", "та", "незграбно"],
        ["небезпечний", "план", "захоплення", "ковбаси"],
        ["бігти", "по", "колу", "з", "ножицями"],
        ["викликати", "доброзичливого", "домашнього", "дракона"],
        ["підкупити", "охоронця", "свіжими", "пончиками"],
        ["викрасти", "всі", "ліві", "шкарпетки"],
        ["вибухати", "від", "нестримного", "ентузіазму"],
        ["трагічне", "непорозуміння", "щодо", "гравітації"],
        ["боротися", "зі", "злочинністю", "в", "пухнастих", "капцях"],
        ["шепотіти", "таємниці", "гарячому", "тостеру"],

        // Essential Connectors, Modifiers, Pronouns & Auxiliaries
        ["і", "та", "також", "разом"],
        ["але", "проте", "однак", "крім"],
        ["бо", "тому", "що", "через", "це"],
        ["щоб", "аби", "якби", "коли"],
        ["дуже", "надзвичайно", "абсолютно", "зовсім"],
        ["завжди", "вічно", "постійно", "усюди"],
        ["ніколи", "ніхто", "ніде", "ніщо"],
        ["просто", "лише", "тільки", "навіть"],
        ["раптом", "миттєво", "швидко", "нарешті"],
        ["це", "було", "буде", "є"],
        ["треба", "можна", "варто", "мусимо"],
        ["без", "з", "під", "над"],
        ["наш", "ваш", "їхній", "мій"],
        ["точно", "справді", "дійсно", "чесно"],
        ["майже", "ледве", "трохи", "занадто"],
        ["кожен", "всі", "хтось", "щось"]
    ]
};

// Backward-compatible alias for 'ua'
FALLBACK_WORDS.ua = FALLBACK_WORDS.uk;
