
import { MIN_ANSWER_WORDS, MIN_PLAYERS, MAX_PLAYERS } from './lib/config.js';

const LANGUAGES = { EN: 'en', UK: 'uk', UA: 'ua' };
export const UI_TEXT = {
  [LANGUAGES.EN]: {
    appName: "Word Scramble Party Game", selectLanguage: "Select Language", createHostDisplay: "Create & Host Display", joinAsPlayer: "Join as Player", enterGameId: "Enter 4-Digit Game ID", enterYourName: "Enter Your Name", join: "Join", gameId: "Game ID", waitingForHost: "Waiting for the Host to start the game...", players: "Players", score: "Score", host: "Host", theme: "Theme", colorTheme: "Color Theme", selectTheme: "Select Theme", customTheme: "Or Enter a Custom Theme", startGame: "Start Game", round: "Round", questionPhase: "Question Phase", answerTheQuestions: "Answer the following questions", minWordsWarning: `Answer must be at least ${MIN_ANSWER_WORDS} words.`, battlePhase: "Battle Phase", answering: "Answering", answered: "Answered", battlePrompt: "Battle Prompt", wordBank: "Word Bank", yourAnswer: "Your Answer", submitBattleAnswer: "Submit Battle Answer", waitingForCompetitors: "Waiting for competitors to submit answers...", votingPhase: "Voting Phase", voteForBestAnswer: "Vote for the Best Answer", results: "Results", winner: "Winner", rank: "Rank", timeRemaining: "Time Remaining", connectedPlayers: "Connected Players", howToConnect: "How to Connect", openBrowserTo: "Open a browser on any device on this network to:", orEnterId: "And enter Game ID:", lobbyFull: "Lobby is full.", gameNotFound: "Game not found.", gameAlreadyStarted: "Game has already started.", serverBusy: "Server is currently at maximum capacity. Please try again in a few moments.", nameRequired: "Please enter a name.", playerCountInvalid: `Need ${MIN_PLAYERS} to ${MAX_PLAYERS} players to start.`, themeNotSet: "Please select a theme.", youAreTheHost: "You are the Host!", waitingForPlayers: "Waiting for players to join...", waitingForAnswers: "Waiting for other players...", waitingForBattleAnswers: "Waiting for battle answers...", waitingForVotes: "Waiting for votes...", battleBetween: "Battle between {c1} and {c2}", and: "and", tie: "It's a tie!", noWinner: "No winner this battle.", finalScores: "Final Scores", submit: "Submit", errorOccurred: "An error occurred", reconnecting: "Reconnecting...", reconnectSuccess: "Reconnected successfully!", reconnectFailed: "Failed to reconnect. Please join again.", yourBattleAnswer: "Your Battle Answer:", opponentBattleAnswer: "Opponent's Battle Answer:", voteFor: "Vote for", chosenTheme: "Chosen Theme", waitingForTheme: "Waiting for the Host to select a theme...", yourTurnToAnswerBattle: "It's your turn to answer!", yourTurnToVote: "It's your turn to vote!", hostScreen: "Host Screen", lobbyScreen: "Lobby", connecting: "Connecting to server...", notEnoughPlayers: `Not enough players (min ${MIN_PLAYERS}).`, tooManyPlayers: `Too many players (max ${MAX_PLAYERS}).`, roundStatus: "Round {currentRound}/3", answeringQuestion: "Question {currentQ}/{totalQ}", battleStatusAnswering: "Battles: Answering", battleStatusVoting: "Battles: Voting", finishedRound: "Finished Round {currentRound}", battleReveal: "Battle Results", answerFrom: "Answer From", vote: "Vote", pleaseWait: "Please wait...", getReadyTitle: "Get Ready!", getReadySubtitle: "Round {currentRound} is coming up!", battleGetReadyTitle: "Battle Incoming!", sillyMode: "Silly Mode", sillyModeDesc: "Generate wacky and absurd questions.", chooseAvatar: "Choose an Avatar", votedForYou: "Voted for you!", is18PlusMode: "18+ Mode", is18PlusModeDesc: "Generate adult-oriented themes & questions.", is18PlusModeWarning: "Warning: Content may be edgy or suggestive.", words: "Words", waitingFor: "Waiting for", prompt: "Prompt", invalidAvatar: "Please select an avatar.", GENERATION_FAILED_PERMANENTLY: "The AI failed to create the round after multiple attempts. Returning to lobby. Please try starting the game again.", nameTaken: "This name is already taken.", avatarTaken: "This avatar is already taken.", generatingThemes: "Generating new themes...", mainMenu: "Main Menu", gameOver: "Game Over", playAgain: "Play Again", restartingGame: "Restarting Game...", gameClosedInactivity: "Game was closed due to inactivity.", watchingBattle: "Watching the battle between {c1} and {c2}", waitingForOtherVotes: "Waiting for other players to vote...", endGame: "End Game", confirmEndGame: "Are you sure you want to end this game for everyone?", gameEndedByHost: "The host has ended the game.", sendReaction: "Send Reaction",
    closeLobby: "Close Lobby",
    confirmCloseLobby: "Are you sure you want to close this lobby? All players will be kicked.",
    slowpokeMode: "Slowpoke Mode", slowpokeModeDesc: "Increases all timers for a relaxed pace.",
    tvMode: "TV / Low Power Mode", tvModeDesc: "Optimizes performance on Smart TV browsers by disabling heavy 3D background grids and GPU blurs.",
    finalRound: "Final Round", finalBattle: "Final Battle", finalBattleScenario: "Scenario", finalBattlePrompt: "Dialog Prompt", completeTheDialogue: "Complete the Dialogue", submitFinalAnswer: "Submit Final Answer", waitingForFinalAnswers: "Waiting for final answers...", voteForBestDialogue: "Vote for the Best Dialogue", finalBattleWinner: "Final Battle Winner",
    dragToRemove: "Drag here to remove",
    disconnected: "DISCONNECTED",
    answerA: "Answer A",
    answerB: "Answer B",
    answerC: "Answer C",
    answerD: "Answer D",
    showdownLabel: "⚡ 1-on-1 Showdown",
    brawlLabel: "💥 3-Way Brawl",
    quadLabel: "🔥 4-Way Brawl",
    voteForThisAnswer: "Vote for this Answer",
    winnerExclamation: "WINNER!",
    yourRank: "Your Rank",
    votingGetReadyTitle: "Get Ready to Vote!",
    allBattles: "All Battles",
    noAnswerSubmitted: "No answer submitted",
    viewBattleHistory: "View Battle History",
    battleHistory: "Battle History",
    backToScores: "Back to Scores",
    saveAsImage: "Save as Image",
    saveAsImageVertical: "Save Vertical",
    saveAsImageLandscape: "Save Landscape",
    saving: "Saving...",
    clear: "Clear",
    clearWorkspace: "Clear All",
    promptWordsLabel: "Prompt Words (tap to use):",
    wordRoyalties: "Word Royalties",
    rainbowBonus: "Rainbow Variety Bonus",
    rainbowBadge: "🌈 Rainbow Bonus",
    votesBreakdown: "Votes",
    winBonusBreakdown: "Win",
    sweepBonusBreakdown: "Sweep",
    rainbowBonusBreakdown: "Rainbow",
    clickWordsHint: "Click words to build your answer",
    clickWordsHintFinal: "Click words to add them here",
    undo: "Undo",
    shuffleBank: "Shuffle",
    reroll: "Re-Roll",
    rerollQuestion: "Re-Roll Question (1 left)",
    rerollsLeft: "Re-Rolls",
    votesLockedIn: "Votes Locked In",
    playersVoted: "{voted} / {total} Players Voted",
    votedBadge: "VOTED",
    reloadTopics: "Reload Themes",
    reloadThemes: "Reload Themes",
    randomTheme: "Random",
    timeBoost: "+30s",
    timeBoostUsed: "{name} added +30s to the round!",
    timeBoostAlreadyUsed: "+30s already used",
    rotateDeviceHint: "Tip: Rotate device to landscape for full TV display view",
    retryConnection: "Tap to Reconnect",
    promptTooltip: "💡 Tip: You can tap words from the prompt to use them in your answer!",
    customThemeHostHint: "Host can also enter a custom theme on their device",
    backToMenu: "Back to Menu",
    gotIt: "Got it!",
    movieTitle: "Movie Title",
    movieTagline: "Movie Tagline",
    superlativesTitle: "Accolades & Awards",
    ammoFactoryTitle: "🎯 The Ammo Factory",
    ammoFactoryDesc: "Authored words that powered the most winning battles!",
    rainbowAlchemistTitle: "🌈 The Rainbow Alchemist",
    rainbowAlchemistDesc: "Master of combining words from 3+ different players!",
    cleanSweeperTitle: "🧹 The Clean Sweeper",
    cleanSweeperDesc: "Dominated the room with 100% unanimous battle wins!",
    minimalistTitle: "🪶 The Minimalist",
    minimalistDesc: "Won a battle with the shortest, punchiest answer!",
    shakespeareTitle: "💬 The Shakespeare",
    shakespeareDesc: "Crafted the most epic, long-winded winning masterpiece!",
    howToPlay: "How to Play",
    backToLobby: "Back to Lobby",
    confirmCharacter: "Confirm Character",
    changeCharacter: "Change Character",
    editName: "Edit Name",
    save: "Save",
    cancel: "Cancel",
    instructionsTitle: "How to Play",
    instructions1Title: "Fuel the Chaos (Question Phase)",
    instructions1Text: "Answer weird questions with at least 5 words. Every word you write is split into tiles to power opponents' word banks!",
    instructions2Title: "Craft the Punchlines (Battle Phase)",
    instructions2Text: "Face off in 1v1 or 3-way battles. Build the ultimate punchline using tiles from opponents' answers or words from the prompt.",
    instructions3Title: "Vote & Score (Voting Phase)",
    instructions3Text: "Vote on the funniest punchline in other battles. Score big points for winning votes, fast submissions, and uniting 3+ players' words.",
    instructions4Title: "⚡ One-Time Powerups & Word Royalties",
    instructionsGoal: "🏆 The player with the highest score after 3 rounds is crowned Champion!",
    oneTimePerGame: "1x per game",
    powerupRerollTitle: "Question Re-Roll",
    powerupRerollDesc: "Swap an unwanted question in the Question phase for a fresh one.",
    powerupTimeBoostTitle: "+30s Time Boost",
    powerupTimeBoostDesc: "Extend the timer by 30 seconds during Question or Battle Answering phases for all players.",
    powerupRoyaltiesTitle: "Word Royalties (+50 pts)",
    powerupRoyaltiesDesc: "Earn +50 bonus points whenever an opponent uses your words in a winning punchline!",
    runnerUp: "Runner Up",
    champion: "Champion",
    podium: "Podium",
    leaderboardRoster: "Leaderboard Roster",
    promptTappingHint: "💡 You can also tap words from the prompt above!",
    minWordsRequirement: "min 5",
    readyToSubmit: "READY",
    wordsNeeded: "more words needed",
    victoryRoyale: "VICTORY ROYALE!",
    greatGame: "GREAT GAME!",
    onThePodium: "ON THE PODIUM!",
    wellPlayed: "WELL PLAYED! (GG)",
    thanksForPlaying: "Great battle of words! Thank you for playing.",
    waitingForHostToRestart: "Waiting for host to start a new game...",
    pts: "PTS",
    prepareControllers: "Prepare your controllers",
    ready: "READY!",
    thinking: "Thinking...",
    finalBattleTheme: "FINAL BATTLE PREMISE",
    anonymous: "ANONYMOUS",
    tapOptionOnPhone: "Tap {label} on Phone",
    voters: "Voters",
    noVotes: "No votes",
    place: "PLACE",
    participant: "PARTICIPANT",
    tagline: "Tagline",
    title: "Title",
    promptWords: "Prompt Words",
    saveProfile: "SAVE PROFILE",
    editProfile: "EDIT PROFILE",
    linkCopied: "Link copied to clipboard!",
    copyGameLink: "Copy game link:",
    copy: "Copy",
    allAnswersSubmitted: "READY!",
    youAreCompeting: "YOU ARE IN THIS BATTLE!",
    voteSubmitted: "VOTE SUBMITTED!",
    duoLabel: "⚡ 1-ON-1 SHOWDOWN",
    moviePitch: "MOVIE PREMISE",
    youWonTheBattle: "👑 YOU WON THE BATTLE!",
    changeAvatar: "Change Avatar",
    realTimePartyGame: "REAL-TIME MULTIPLAYER PARTY GAME",
    joinOnYourPhone: "Join on your phone at",
    connected: "CONNECTED",
    generatingRoundMessages: [
      "Reticulating splines...",
      "Teaching the AI about sarcasm...",
      "Polishing the word-scrambler...",
      "Consulting the digital oracle...",
      "Warming up the creativity cores...",
      "Shuffling the dictionary...",
      "Asking the hive-mind for ideas...",
      "Brewing a fresh pot of prompts...",
      "Don't worry, the AI is a professional...",
      "Generating giggles and gasps...",
      "Herding rogue data points..."
    ],
  },
  [LANGUAGES.UK]: {
    appName: "Вечірка Слів: Скрембл",
    selectLanguage: "Обрати мову",
    createHostDisplay: "Створити та хостити",
    joinAsPlayer: "Приєднатись до гри",
    enterGameId: "Введіть 4-значний ID гри",
    enterYourName: "Введіть ваше ім'я",
    join: "Приєднатись",
    gameId: "ID Гри",
    waitingForHost: "Очікування на старт гри від хоста...",
    players: "Гравці",
    score: "Рахунок",
    host: "Хост",
    theme: "Тема",
    colorTheme: "Стиль",
    selectTheme: "Оберіть тему",
    customTheme: "Або введіть власну тему",
    startGame: "Почати гру",
    round: "Раунд",
    questionPhase: "Фаза запитань",
    answerTheQuestions: "Дайте відповіді на наступні запитання",
    minWordsWarning: `Відповідь повинна містити щонайменше ${MIN_ANSWER_WORDS} слів.`,
    battlePhase: "Фаза битви",
    answering: "Відповідь",
    answered: "Відповіли",
    battlePrompt: "Тема битви",
    wordBank: "Банк слів",
    yourAnswer: "Ваша відповідь",
    submitBattleAnswer: "Надіслати відповідь",
    waitingForCompetitors: "Очікування на відповіді від суперників...",
    votingPhase: "Фаза голосування",
    voteForBestAnswer: "Голосуйте за найкращу відповідь",
    results: "Результати",
    winner: "Переможець",
    rank: "Місце",
    timeRemaining: "Часу залишилось",
    connectedPlayers: "Під'єднані гравці",
    howToConnect: "Як під'єднатись",
    openBrowserTo: "Відкрийте браузер на будь-якому пристрої в цій мережі:",
    orEnterId: "Та введіть ID гри:",
    lobbyFull: "Лобі повне.",
    gameNotFound: "Гру не знайдено.",
    gameAlreadyStarted: "Гра вже почалася.",
    serverBusy: "Сервер наразі перевантажений. Будь ласка, спробуйте знову за хвилину.",
    nameRequired: "Будь ласка, введіть ім'я.",
    playerCountInvalid: `Потрібно від ${MIN_PLAYERS} до ${MAX_PLAYERS} гравців для старту.`,
    themeNotSet: "Будь ласка, оберіть тему.",
    youAreTheHost: "Ви - хост!",
    waitingForPlayers: "Очікування на гравців...",
    waitingForAnswers: "Очікування на відповіді від інших гравців...",
    waitingForBattleAnswers: "Очікування на відповіді для битви...",
    waitingForVotes: "Очікування на голоси...",
    battleBetween: "Битва між {c1} та {c2}",
    and: "та",
    tie: "Нічия!",
    noWinner: "У цій битві немає переможця.",
    finalScores: "Фінальний рахунок",
    submit: "Надіслати",
    errorOccurred: "Сталася помилка",
    reconnecting: "Перепідключення...",
    reconnectSuccess: "Успішно перепідключено!",
    reconnectFailed: "Не вдалося перепідключитися. Будь ласка, приєднайтесь знову.",
    yourBattleAnswer: "Ваша відповідь у битві:",
    opponentBattleAnswer: "Відповідь суперника:",
    voteFor: "Голосувати за",
    chosenTheme: "Обрана тема",
    waitingForTheme: "Очікування на вибір теми від хоста...",
    yourTurnToAnswerBattle: "Ваша черга відповідати!",
    yourTurnToVote: "Ваша черга голосувати!",
    hostScreen: "Екран хоста",
    lobbyScreen: "Лобі",
    connecting: "Підключення до сервера...",
    notEnoughPlayers: `Недостатньо гравців (мін ${MIN_PLAYERS}).`,
    tooManyPlayers: `Забагато гравців (макс ${MAX_PLAYERS}).`,
    roundStatus: "Раунд {currentRound}/3",
    answeringQuestion: "Запитання {currentQ}/{totalQ}",
    battleStatusAnswering: "Битви: Відповідь",
    battleStatusVoting: "Битви: Голосування",
    finishedRound: "Раунд {currentRound} завершено",
    battleReveal: "Результати битви",
    answerFrom: "Відповідь від",
    vote: "Голос",
    pleaseWait: "Будь ласка, зачекайте...",
    getReadyTitle: "Приготуйтесь!",
    getReadySubtitle: "Наближається раунд {currentRound}!",
    battleGetReadyTitle: "Наближається битва!",
    sillyMode: "Режим дурниць",
    sillyModeDesc: "Генерувати дивакуваті та абсурдні запитання.",
    chooseAvatar: "Оберіть аватар",
    votedForYou: "Проголосували за вас!",
    is18PlusMode: "Режим 18+",
    is18PlusModeDesc: "Генерувати теми та запитання для дорослих.",
    is18PlusModeWarning: "Увага: Контент може бути гострим або провокативним.",
    words: "Слова",
    waitingFor: "Очікування на",
    prompt: "Завдання",
    invalidAvatar: "Будь ласка, оберіть аватар.",
    GENERATION_FAILED_PERMANENTLY: "ШІ не зміг створити раунд після кількох спроб. Повернення до лобі. Спробуйте почати гру знову.",
    nameTaken: "Це ім'я вже зайняте.",
    avatarTaken: "Цей аватар вже зайнятий.",
    generatingThemes: "Генерація нових тем...",
    mainMenu: "Головне меню",
    gameOver: "Гру завершено",
    playAgain: "Грати знову",
    restartingGame: "Перезапуск гри...",
    gameClosedInactivity: "Гру було закрито через неактивність.",
    watchingBattle: "Спостереження за битвою: {c1} проти {c2}",
    waitingForOtherVotes: "Очікування на голоси інших гравців...",
    endGame: "Завершити гру",
    confirmEndGame: "Ви впевнені, що хочете завершити гру для всіх?",
    closeLobby: "Закрити лобі",
    confirmCloseLobby: "Ви впевнені, що хочете закрити це лобі? Усіх гравців буде від'єднано.",
    gameEndedByHost: "Хост завершив гру.",
    sendReaction: "Надіслати реакцію",
    slowpokeMode: "Режим 'Slowpoke'",
    slowpokeModeDesc: "Збільшує всі таймери для спокійного темпу.",
    tvMode: "Режим для ТБ / Економія",
    tvModeDesc: "Оптимізує швидкодію на браузерах Smart TV, вимикаючи важку 3D-сітку та складні ефекти.",
    rotateDeviceHint: "Порада: поверніть пристрій горизонтально для повного огляду",
    finalRound: "Фінальний раунд",
    finalBattle: "Фінальна битва",
    finalBattleScenario: "Сценарій",
    finalBattlePrompt: "Діалог",
    completeTheDialogue: "Завершіть діалог",
    submitFinalAnswer: "Надіслати фінальну відповідь",
    waitingForFinalAnswers: "Очікування на фінальні відповіді...",
    voteForBestDialogue: "Голосуйте за найкращий діалог",
    finalBattleWinner: "Переможець фінальної битви",
    dragToRemove: "Перетягніть для видалення",
    disconnected: "ВІДКЛЮЧЕНО",
    answerA: "Відповідь A",
    answerB: "Відповідь Б",
    answerC: "Відповідь В",
    answerD: "Відповідь Г",
    showdownLabel: "⚡ Дуель 1-на-1",
    brawlLabel: "💥 Потрійна Битва",
    quadLabel: "🔥 Четверна Битва",
    voteForThisAnswer: "Голосувати за цю відповідь",
    winnerExclamation: "ПЕРЕМОЖЕЦЬ!",
    yourRank: "Ваше місце",
    votingGetReadyTitle: "Приготуйтесь голосувати!",
    allBattles: "Усі Битви",
    noAnswerSubmitted: "Відповідь не надіслано",
    viewBattleHistory: "Історія Битв",
    battleHistory: "Історія Битв",
    backToScores: "Назад до результатів",
    saveAsImage: "Зберегти як зображення",
    saveAsImageVertical: "Зберегти вертикально",
    saveAsImageLandscape: "Зберегти горизонтально",
    saving: "Збереження...",
    clear: "Очистити",
    clearWorkspace: "Очистити все",
    promptWordsLabel: "Слова із завдання (натисніть):",
    wordRoyalties: "Роялті за слова",
    rainbowBonus: "Веселковий бонус за різноманіття",
    rainbowBadge: "🌈 Бонус Веселка",
    votesBreakdown: "Голоси",
    winBonusBreakdown: "Перемога",
    sweepBonusBreakdown: "Чиста перемога",
    rainbowBonusBreakdown: "Веселка",
    clickWordsHint: "Натискайте слова, щоб скласти відповідь",
    clickWordsHintFinal: "Натискайте слова, щоб додати їх сюди",
    undo: "Скасувати",
    shuffleBank: "Перемішати",
    reroll: "Замінити",
    rerollQuestion: "Замінити запитання (1 спроба)",
    rerollsLeft: "Заміни",
    votesLockedIn: "Голосів прийнято",
    playersVoted: "Проголосувало {voted} з {total}",
    votedBadge: "ПРОГОЛОСОВАНО",
    reloadTopics: "Оновити теми",
    reloadThemes: "Оновити теми",
    randomTheme: "Випадкова",
    timeBoost: "+30с",
    timeBoostUsed: "{name} додає +30с до раунду!",
    timeBoostAlreadyUsed: "+30с вже використано",
    retryConnection: "Спробувати підключитися",
    promptTooltip: "💡 Підказка: Ви також можете натискати слова із завдання!",
    customThemeHostHint: "Хост також може ввести власну тему на своєму пристрої",
    backToMenu: "Назад до меню",
    gotIt: "Зрозуміло!",
    movieTitle: "Назва фільму",
    movieTagline: "Слоган фільму",
    superlativesTitle: "Особливі Нагороди",
    ammoFactoryTitle: "🎯 Фабрика Боєприпасів",
    ammoFactoryDesc: "Слова цього гравця принесли найбільше перемог іншим!",
    rainbowAlchemistTitle: "🌈 Веселковий Алхімік",
    rainbowAlchemistDesc: "Майстер поєднання слів від 3+ різних друзів!",
    cleanSweeperTitle: "🧹 Чистий Тріумфатор",
    cleanSweeperDesc: "Здобув найбільше 100% одноголосних перемог у битвах!",
    minimalistTitle: "🪶 Мінімаліст",
    minimalistDesc: "Виграв битву найкоротшою та найвлучнішою відповіддю!",
    shakespeareTitle: "💬 Шекспір",
    shakespeareDesc: "Створив найбільш епічний та багатослівний шедевр-переможець!",
    howToPlay: "Як грати",
    backToLobby: "Назад до лобі",
    confirmCharacter: "Підтвердити персонажа",
    changeCharacter: "Змінити персонажа",
    editName: "Змінити ім'я",
    save: "Зберегти",
    cancel: "Скасувати",
    instructionsTitle: "Як грати",
    instructions1Title: "Створюй Хаос (Фаза Запитань)",
    instructions1Text: "Відповідай на дивні запитання (мінімум 5 слів). Кожне твоє слово перетворюється на плитки-боєприпаси для опонентів!",
    instructions2Title: "Збирай Панчлайни (Фаза Битв)",
    instructions2Text: "Змагайся у дуелях 1 на 1 або потрійних битвах. Складай смішні відповіді зі слів суперників або слів самого завдання.",
    instructions3Title: "Голосуй та Перемагай (Голосування)",
    instructions3Text: "Голосуй за найсмішніший панчлайн у битвах опонентів. Заробляй бали за переможні голоси, швидкість та комбінації від 3+ авторів.",
    instructions4Title: "⚡ Одноразові Бонуси та Роялті",
    instructionsGoal: "🏆 Гравець із найбільшою кількістю балів після 3 раундів стає Чемпіоном!",
    oneTimePerGame: "1 раз на гру",
    powerupRerollTitle: "Рерол Запитання",
    powerupRerollDesc: "Заміни незручне запитання у фазі запитань на абсолютно нове.",
    powerupTimeBoostTitle: "+30с Буст Часу",
    powerupTimeBoostDesc: "Додай 30 секунд до таймера у фазі запитань або складання відповідей для всіх гравців.",
    powerupRoyaltiesTitle: "Роялті за Слова (+50 балів)",
    powerupRoyaltiesDesc: "Отримуй +50 бонусних балів щоразу, коли інший гравець перемагає завдяки твоїм словам!",
    runnerUp: "Фіналіст",
    champion: "Чемпіон",
    podium: "Призер",
    leaderboardRoster: "Таблиця учасників",
    promptTappingHint: "💡 Ви також можете натискати слова із завдання вище!",
    minWordsRequirement: "мін 5",
    readyToSubmit: "ГОТОВО",
    wordsNeeded: "ще слів потрібно",
    victoryRoyale: "ВЕЛИКА ПЕРЕМОГА!",
    greatGame: "ЧУДОВА ГРА!",
    onThePodium: "НА ПОДІУМІ!",
    wellPlayed: "ДЯКУЄМО ЗА ГРУ! (GG)",
    thanksForPlaying: "Чудова битва слів! Дякуємо за гру.",
    movieGenre: "Жанр фільму",
    pts: "БАЛІВ",
    prepareControllers: "Підготуйте ваші телефони",
    ready: "ГОТОВИЙ!",
    thinking: "Думає...",
    finalBattleTheme: "СЮЖЕТ ФІНАЛЬНОЇ БИТВИ",
    anonymous: "АНОНІМНО",
    tapOptionOnPhone: "Оберіть {label} на телефоні",
    voters: "Голосів",
    noVotes: "Немає голосів",
    place: "МІСЦЕ",
    participant: "УЧАСНИК",
    tagline: "Слоган",
    title: "Назва",
    promptWords: "Слова із завдання",
    saveProfile: "ЗБЕРЕГТИ ПРОФІЛЬ",
    editProfile: "РЕДАГУВАТИ ПРОФІЛЬ",
    linkCopied: "Посилання скопійовано в буфер обміну!",
    copyGameLink: "Скопіюйте посилання на гру:",
    copy: "Копіювати",
    allAnswersSubmitted: "ГОТОВО!",
    youAreCompeting: "ВИ БЕРЕТЕ УЧАСТЬ У ЦІЙ БИТВІ!",
    voteSubmitted: "ГОЛОС ПРИЙНЯТО!",
    duoLabel: "⚡ ДУЕЛЬ 1-НА-1",
    moviePitch: "СЮЖЕТ ФІЛЬМУ",
    youWonTheBattle: "👑 ВИ ПЕРЕМОГЛИ У БИТВІ!",
    changeAvatar: "Змінити аватар",
    realTimePartyGame: "ГРА ДЛЯ ВЕЧІРОК В РЕАЛЬНОМУ ЧАСІ",
    joinOnYourPhone: "Приєднуйтесь з телефону за адресою",
    connected: "ПІДКЛЮЧЕНО",
    generatingRoundMessages: [
        "Ретранслюємо сплайни...",
        "Навчаємо ШІ сарказму...",
        "Поліруємо слово-скремблер...",
        "Консультуємось з цифровим оракулом...",
        "Розігріваємо ядра творчості...",
        "Тасуємо словник...",
        "Запитуємо ідеї у колективного розуму...",
        "Заварюємо свіжу порцію завдань...",
        "Не хвилюйтесь, ШІ - професіонал...",
        "Генеруємо сміх та подив...",
        "Зганяємо в купу блукаючі дані..."
    ],
  }
};

UI_TEXT[LANGUAGES.UA] = UI_TEXT[LANGUAGES.UK];