

import { MIN_ANSWER_WORDS, MIN_PLAYERS, MAX_PLAYERS } from './lib/config.js';

const LANGUAGES = { EN: 'en', UK: 'uk' };
export const UI_TEXT = {
  [LANGUAGES.EN]: {
    appName: "Word Scramble Party Game", selectLanguage: "Select Language", createHostDisplay: "Create & Host Display", joinAsPlayer: "Join as Player", enterGameId: "Enter 4-Digit Game ID", enterYourName: "Enter Your Name", join: "Join", gameId: "Game ID", waitingForHost: "Waiting for the Host to start the game...", players: "Players", score: "Score", host: "Host", theme: "Theme", colorTheme: "Color Theme", selectTheme: "Select Theme", customTheme: "Or Enter a Custom Theme", startGame: "Start Game", round: "Round", questionPhase: "Question Phase", answerTheQuestions: "Answer the following questions", minWordsWarning: `Answer must be at least ${MIN_ANSWER_WORDS} words.`, battlePhase: "Battle Phase", answering: "Answering", answered: "Answered", battlePrompt: "Battle Prompt", wordBank: "Word Bank", yourAnswer: "Your Answer", submitBattleAnswer: "Submit Battle Answer", waitingForCompetitors: "Waiting for competitors to submit answers...", votingPhase: "Voting Phase", voteForBestAnswer: "Vote for the Best Answer", results: "Results", winner: "Winner", rank: "Rank", timeRemaining: "Time Remaining", connectedPlayers: "Connected Players", howToConnect: "How to Connect", openBrowserTo: "Open a browser on any device on this network to:", orEnterId: "And enter Game ID:", lobbyFull: "Lobby is full.", gameNotFound: "Game not found.", gameAlreadyStarted: "Game has already started.", nameRequired: "Please enter a name.", playerCountInvalid: `Need ${MIN_PLAYERS} to ${MAX_PLAYERS} players to start.`, themeNotSet: "Please select a theme.", youAreTheHost: "You are the Host!", waitingForPlayers: "Waiting for players to join...", waitingForAnswers: "Waiting for other players...", waitingForBattleAnswers: "Waiting for battle answers...", waitingForVotes: "Waiting for votes...", battleBetween: "Battle between {c1} and {c2}", and: "and", tie: "It's a tie!", noWinner: "No winner this battle.", finalScores: "Final Scores", submit: "Submit", errorOccurred: "An error occurred", reconnecting: "Reconnecting...", reconnectSuccess: "Reconnected successfully!", reconnectFailed: "Failed to reconnect. Please join again.", yourBattleAnswer: "Your Battle Answer:", opponentBattleAnswer: "Opponent's Battle Answer:", voteFor: "Vote for", chosenTheme: "Chosen Theme", waitingForTheme: "Waiting for the Host to select a theme...", yourTurnToAnswerBattle: "It's your turn to answer!", yourTurnToVote: "It's your turn to vote!", hostScreen: "Host Screen", lobbyScreen: "Lobby", connecting: "Connecting to server...", notEnoughPlayers: `Not enough players (min ${MIN_PLAYERS}).`, tooManyPlayers: `Too many players (max ${MAX_PLAYERS}).`, roundStatus: "Round {currentRound}/3", answeringQuestion: "Question {currentQ}/{totalQ}", battleStatusAnswering: "Battles: Answering", battleStatusVoting: "Battles: Voting", finishedRound: "Finished Round {currentRound}", battleReveal: "Battle Results", answerFrom: "Answer From", vote: "Vote", pleaseWait: "Please wait...", getReadyTitle: "Get Ready!", getReadySubtitle: "Round {currentRound} is coming up!", battleGetReadyTitle: "Battle Incoming!", sillyMode: "Silly Mode", sillyModeDesc: "Generate wacky and absurd questions.", chooseAvatar: "Choose an Avatar", votedForYou: "Voted for you!", is18PlusMode: "18+ Mode", is18PlusModeDesc: "Generate adult-oriented themes & questions.", is18PlusModeWarning: "Warning: Content may be edgy or suggestive.", words: "Words", waitingFor: "Waiting for", prompt: "Prompt", invalidAvatar: "Please select an avatar.", GENERATION_FAILED_PERMANENTLY: "The AI failed to create the round after multiple attempts. Returning to lobby. Please try starting the game again.", nameTaken: "This name is already taken.", avatarTaken: "This avatar is already taken.", generatingThemes: "Generating new themes...", mainMenu: "Main Menu", gameOver: "Game Over", playAgain: "Play Again", restartingGame: "Restarting Game...", gameClosedInactivity: "Game was closed due to inactivity.", watchingBattle: "Watching the battle between {c1} and {c2}", waitingForOtherVotes: "Waiting for other players to vote...", endGame: "End Game", confirmEndGame: "Are you sure you want to end this game for everyone?", gameEndedByHost: "The host has ended the game.", sendReaction: "Send Reaction",
    closeLobby: "Close Lobby",
    confirmCloseLobby: "Are you sure you want to close this lobby? All players will be kicked.",
    slowpokeMode: "Slowpoke Mode", slowpokeModeDesc: "Increases all timers for a relaxed pace.",
    tvMode: "TV / Low Power Mode", tvModeDesc: "Optimizes performance on Smart TV browsers by disabling heavy 3D background grids and GPU blurs.",
    finalRound: "Final Round", finalBattle: "Final Battle", finalBattleScenario: "Scenario", finalBattlePrompt: "Dialog Prompt", completeTheDialogue: "Complete the Dialogue", submitFinalAnswer: "Submit Final Answer", waitingForFinalAnswers: "Waiting for final answers...", voteForBestDialogue: "Vote for the Best Dialogue", finalBattleWinner: "Final Battle Winner",
    dragToRemove: "Drag here to remove",
    disconnected: "DISCONNECTED",
    answerA: "Answer A",
    answerB: "Answer B",
    answerC: "Answer C",
    answerD: "Answer D",
    showdownLabel: "⚡ 1-on-1 Showdown",
    brawlLabel: "💥 3-Way Brawl",
    quadLabel: "🔥 4-Way Brawl",
    voteForThisAnswer: "Vote for this Answer",
    winnerExclamation: "WINNER!",
    yourRank: "Your Rank",
    votingGetReadyTitle: "Get Ready to Vote!",
    allBattles: "All Battles",
    noAnswerSubmitted: "No answer submitted",
    viewBattleHistory: "View Battle History",
    battleHistory: "Battle History",
    backToScores: "Back to Scores",
    saveAsImage: "Save as Image",
    saveAsImageVertical: "Save Vertical",
    saveAsImageLandscape: "Save Landscape",
    saving: "Saving...",
    clear: "Clear",
    clearWorkspace: "Clear All",
    promptWordsLabel: "Prompt Words (tap to use):",
    wordRoyalties: "Word Royalties",
    rainbowBonus: "Rainbow Variety Bonus",
    rainbowBadge: "🌈 Rainbow Bonus",
    votesBreakdown: "Votes",
    winBonusBreakdown: "Win",
    sweepBonusBreakdown: "Sweep",
    rainbowBonusBreakdown: "Rainbow",
    clickWordsHint: "Click words to build your answer",
    clickWordsHintFinal: "Click words to add them here",
    undo: "Undo",
    shuffleBank: "Shuffle",
    reroll: "Re-Roll",
    rerollQuestion: "Re-Roll Question (1 left)",
    rerollsLeft: "Re-Rolls",
    votesLockedIn: "Votes Locked In",
    votedBadge: "VOTED",
    superlativesTitle: "Accolades & Awards",
    ammoFactoryTitle: "🎯 The Ammo Factory",
    ammoFactoryDesc: "Authored words that powered the most winning battles!",
    rainbowAlchemistTitle: "🌈 The Rainbow Alchemist",
    rainbowAlchemistDesc: "Master of combining words from 3+ different players!",
    cleanSweeperTitle: "🧹 The Clean Sweeper",
    cleanSweeperDesc: "Dominated the room with 100% unanimous battle wins!",
    minimalistTitle: "🪶 The Minimalist",
    minimalistDesc: "Won a battle with the shortest, punchiest answer!",
    shakespeareTitle: "💬 The Shakespeare",
    shakespeareDesc: "Crafted the most epic, long-winded winning masterpiece!",
    howToPlay: "How to Play",
    backToLobby: "Back to Lobby",
    confirmCharacter: "Confirm Character",
    changeCharacter: "Change Character",
    editName: "Edit Name",
    save: "Save",
    cancel: "Cancel",
    instructionsTitle: "How to Play",
    instructions1Title: "Fuel the Chaos",
    instructions1Text: "You'll get some weird questions. Your job isn't to be honest, it's to be inventive. Every word you write becomes ammo for your opponents' future punchlines.",
    instructions2Title: "Build a Monster... Sentence!",
    instructions2Text: "You'll face off against another player. Your only weapon? Their own words! Stitch together words from their answers to create a new, hysterically funny response.",
    instructions3Title: "Vote & Score",
    instructions3Text: "In other players' battles, you hold the power. Vote for the funniest response. You'll score big points when your own masterpiece of an answer wins its battle.",
    instructionsGoal: "Most points after 3 rounds wins!",
    generatingRoundMessages: [
      "Reticulating splines...",
      "Teaching the AI about sarcasm...",
      "Polishing the word-scrambler...",
      "Consulting the digital oracle...",
      "Warming up the creativity cores...",
      "Shuffling the dictionary...",
      "Asking the hive-mind for ideas...",
      "Brewing a fresh pot of prompts...",
      "Don't worry, the AI is a professional...",
      "Generating giggles and gasps...",
      "Herding rogue data points..."
    ],
  },
  [LANGUAGES.UK]: {
    appName: "Вечірка Слів: Скрембл",
    selectLanguage: "Обрати мову",
    createHostDisplay: "Створити та хостити",
    joinAsPlayer: "Приєднатись до гри",
    enterGameId: "Введіть 4-значний ID гри",
    enterYourName: "Введіть ваше ім'я",
    join: "Приєднатись",
    gameId: "ID Гри",
    waitingForHost: "Очікування на старт гри від хоста...",
    players: "Гравці",
    score: "Рахунок",
    host: "Хост",
    theme: "Тема",
    colorTheme: "Стиль",
    selectTheme: "Оберіть тему",
    customTheme: "Або введіть власну тему",
    startGame: "Почати гру",
    round: "Раунд",
    questionPhase: "Фаза запитань",
    answerTheQuestions: "Дайте відповіді на наступні запитання",
    minWordsWarning: `Відповідь повинна містити щонайменше ${MIN_ANSWER_WORDS} слів.`,
    battlePhase: "Фаза битви",
    answering: "Відповідь",
    answered: "Відповіли",
    battlePrompt: "Тема битви",
    wordBank: "Банк слів",
    yourAnswer: "Ваша відповідь",
    submitBattleAnswer: "Надіслати відповідь",
    waitingForCompetitors: "Очікування на відповіді від суперників...",
    votingPhase: "Фаза голосування",
    voteForBestAnswer: "Голосуйте за найкращу відповідь",
    results: "Результати",
    winner: "Переможець",
    rank: "Місце",
    timeRemaining: "Часу залишилось",
    connectedPlayers: "Під'єднані гравці",
    howToConnect: "Як під'єднатись",
    openBrowserTo: "Відкрийте браузер на будь-якому пристрої в цій мережі:",
    orEnterId: "Та введіть ID гри:",
    lobbyFull: "Лобі повне.",
    gameNotFound: "Гру не знайдено.",
    gameAlreadyStarted: "Гра вже почалася.",
    nameRequired: "Будь ласка, введіть ім'я.",
    playerCountInvalid: `Потрібно від ${MIN_PLAYERS} до ${MAX_PLAYERS} гравців для старту.`,
    themeNotSet: "Будь ласка, оберіть тему.",
    youAreTheHost: "Ви - хост!",
    waitingForPlayers: "Очікування на гравців...",
    waitingForAnswers: "Очікування на відповіді від інших гравців...",
    waitingForBattleAnswers: "Очікування на відповіді для битви...",
    waitingForVotes: "Очікування на голоси...",
    battleBetween: "Битва між {c1} та {c2}",
    and: "та",
    tie: "Нічия!",
    noWinner: "У цій битві немає переможця.",
    finalScores: "Фінальний рахунок",
    submit: "Надіслати",
    errorOccurred: "Сталася помилка",
    reconnecting: "Перепідключення...",
    reconnectSuccess: "Успішно перепідключено!",
    reconnectFailed: "Не вдалося перепідключитися. Будь ласка, приєднайтесь знову.",
    yourBattleAnswer: "Ваша відповідь у битві:",
    opponentBattleAnswer: "Відповідь суперника:",
    voteFor: "Голосувати за",
    chosenTheme: "Обрана тема",
    waitingForTheme: "Очікування на вибір теми від хоста...",
    yourTurnToAnswerBattle: "Ваша черга відповідати!",
    yourTurnToVote: "Ваша черга голосувати!",
    hostScreen: "Екран хоста",
    lobbyScreen: "Лобі",
    connecting: "Підключення до сервера...",
    notEnoughPlayers: `Недостатньо гравців (мін ${MIN_PLAYERS}).`,
    tooManyPlayers: `Забагато гравців (макс ${MAX_PLAYERS}).`,
    roundStatus: "Раунд {currentRound}/3",
    answeringQuestion: "Запитання {currentQ}/{totalQ}",
    battleStatusAnswering: "Битви: Відповідь",
    battleStatusVoting: "Битви: Голосування",
    finishedRound: "Раунд {currentRound} завершено",
    battleReveal: "Результати битви",
    answerFrom: "Відповідь від",
    vote: "Голос",
    pleaseWait: "Будь ласка, зачекайте...",
    getReadyTitle: "Приготуйтесь!",
    getReadySubtitle: "Наближається раунд {currentRound}!",
    battleGetReadyTitle: "Наближається битва!",
    sillyMode: "Режим дурниць",
    sillyModeDesc: "Генерувати дивакуваті та абсурдні запитання.",
    chooseAvatar: "Оберіть аватар",
    votedForYou: "Проголосували за вас!",
    is18PlusMode: "Режим 18+",
    is18PlusModeDesc: "Генерувати теми та запитання для дорослих.",
    is18PlusModeWarning: "Увага: Контент може бути гострим або провокативним.",
    words: "Слова",
    waitingFor: "Очікування на",
    prompt: "Завдання",
    invalidAvatar: "Будь ласка, оберіть аватар.",
    GENERATION_FAILED_PERMANENTLY: "ШІ не зміг створити раунд після кількох спроб. Повернення до лобі. Спробуйте почати гру знову.",
    nameTaken: "Це ім'я вже зайняте.",
    avatarTaken: "Цей аватар вже зайнятий.",
    generatingThemes: "Генерація нових тем...",
    mainMenu: "Головне меню",
    gameOver: "Гру завершено",
    playAgain: "Грати знову",
    restartingGame: "Перезапуск гри...",
    gameClosedInactivity: "Гру було закрито через неактивність.",
    watchingBattle: "Спостереження за битвою: {c1} проти {c2}",
    waitingForOtherVotes: "Очікування на голоси інших гравців...",
    endGame: "Завершити гру",
    confirmEndGame: "Ви впевнені, що хочете завершити гру для всіх?",
    closeLobby: "Закрити лобі",
    confirmCloseLobby: "Ви впевнені, що хочете закрити це лобі? Усіх гравців буде від'єднано.",
    gameEndedByHost: "Хост завершив гру.",
    sendReaction: "Надіслати реакцію",
    slowpokeMode: "Режим 'Slowpoke'",
    slowpokeModeDesc: "Збільшує всі таймери для спокійного темпу.",
    tvMode: "Режим для ТБ / Економія",
    tvModeDesc: "Оптимізує швидкодію на браузерах Smart TV, вимикаючи важку 3D-сітку та складні ефекти.",
    finalRound: "Фінальний раунд",
    finalBattle: "Фінальна битва",
    finalBattleScenario: "Сценарій",
    finalBattlePrompt: "Діалог",
    completeTheDialogue: "Завершіть діалог",
    submitFinalAnswer: "Надіслати фінальну відповідь",
    waitingForFinalAnswers: "Очікування на фінальні відповіді...",
    voteForBestDialogue: "Голосуйте за найкращий діалог",
    finalBattleWinner: "Переможець фінальної битви",
    dragToRemove: "Перетягніть для видалення",
    disconnected: "ВІДКЛЮЧЕНО",
    answerA: "Відповідь A",
    answerB: "Відповідь Б",
    answerC: "Відповідь В",
    answerD: "Відповідь Г",
    showdownLabel: "⚡ Дуель 1-на-1",
    brawlLabel: "💥 Потрійна Битва",
    quadLabel: "🔥 Четверна Битва",
    voteForThisAnswer: "Голосувати за цю відповідь",
    winnerExclamation: "ПЕРЕМОЖЕЦЬ!",
    yourRank: "Ваше місце",
    votingGetReadyTitle: "Приготуйтесь голосувати!",
    allBattles: "Усі Битви",
    noAnswerSubmitted: "Відповідь не надіслано",
    viewBattleHistory: "Історія Битв",
    battleHistory: "Історія Битв",
    backToScores: "Назад до результатів",
    saveAsImage: "Зберегти як зображення",
    saveAsImageVertical: "Зберегти вертикально",
    saveAsImageLandscape: "Зберегти горизонтально",
    saving: "Збереження...",
    clear: "Очистити",
    clearWorkspace: "Очистити все",
    promptWordsLabel: "Слова із завдання (натисніть):",
    wordRoyalties: "Роялті за слова",
    rainbowBonus: "Веселковий бонус за різноманіття",
    rainbowBadge: "🌈 Бонус Веселка",
    votesBreakdown: "Голоси",
    winBonusBreakdown: "Перемога",
    sweepBonusBreakdown: "Чиста перемога",
    rainbowBonusBreakdown: "Веселка",
    clickWordsHint: "Натискайте слова, щоб скласти відповідь",
    clickWordsHintFinal: "Натискайте слова, щоб додати їх сюди",
    undo: "Скасувати",
    shuffleBank: "Перемішати",
    reroll: "Замінити",
    rerollQuestion: "Замінити запитання (1 спроба)",
    rerollsLeft: "Заміни",
    votesLockedIn: "Голосів прийнято",
    votedBadge: "ПРОГОЛОСОВАНО",
    superlativesTitle: "Особливі Нагороди",
    ammoFactoryTitle: "🎯 Фабрика Боєприпасів",
    ammoFactoryDesc: "Слова цього гравця принесли найбільше перемог іншим!",
    rainbowAlchemistTitle: "🌈 Веселковий Алхімік",
    rainbowAlchemistDesc: "Майстер поєднання слів від 3+ різних друзів!",
    cleanSweeperTitle: "🧹 Чистий Тріумфатор",
    cleanSweeperDesc: "Здобув найбільше 100% одноголосних перемог у битвах!",
    minimalistTitle: "🪶 Мінімаліст",
    minimalistDesc: "Виграв битву найкоротшою та найвлучнішою відповіддю!",
    shakespeareTitle: "💬 Шекспір",
    shakespeareDesc: "Створив найбільш епічний та багатослівний шедевр-переможець!",
    howToPlay: "Як грати",
    backToLobby: "Назад до лобі",
    confirmCharacter: "Підтвердити персонажа",
    changeCharacter: "Змінити персонажа",
    editName: "Змінити ім'я",
    save: "Зберегти",
    cancel: "Скасувати",
    instructionsTitle: "Як грати",
    instructions1Title: "Створюй Хаос",
    instructions1Text: "Ти отримаєш дивні запитання. Твоє завдання — не бути чесним, а бути винахідливим. Кожне написане тобою слово стає боєприпасом для майбутніх жартів твоїх опонентів.",
    instructions2Title: "Створи Монстра... з Слів!",
    instructions2Text: "Ти зіткнешся з іншим гравцем. Твоя єдина зброя? Його власні слова! Зшивай слова з його відповідей, щоб створити нову, істерично смішну відповідь.",
    instructions3Title: "Голосуй та Заробляй",
    instructions3Text: "Під час битв інших гравців влада в твоїх руках. Голосуй за найсмішнішу відповідь. Ти отримаєш бали, коли твій власний шедевр переможе у своїй битві.",
    instructionsGoal: "Найбільше очок за 3 раунди - перемога!",
    generatingRoundMessages: [
        "Ретранслюємо сплайни...",
        "Навчаємо ШІ сарказму...",
        "Поліруємо слово-скремблер...",
        "Консультуємось з цифровим оракулом...",
        "Розігріваємо ядра творчості...",
        "Тасуємо словник...",
        "Запитуємо ідеї у колективного розуму...",
        "Заварюємо свіжу порцію завдань...",
        "Не хвилюйтесь, ШІ - професіонал...",
        "Генеруємо сміх та подив...",
        "Зганяємо в купу блукаючі дані..."
    ],
  }
};